### ISSUE TITLE
Connection Limits

### ISSUE THREAD

**Issue by Top64** [foundryvtt/pixels#9]
Currently, a limitation of 3 Pixels is the limitation in Google Chrome and Edge.

[Pixel Pixele30e1ec0] Status changed to connecting    manager.mjs:92
index.js:2 [Pixel Pixele30e1ec0] Status changed to disconnected
foundry.js:71791 PixelConnectError: Pixel Pixele30e1ec0: Pixel Pixele30e1ec0: Connection error. Connection Error: Connection attempt failed.
    at yt.connect (index.js:2:76953)
    at async PixelsManager.connect (manager.mjs:92:5)
    at async PixelsManager.request (manager.mjs:79:5)
    at async #connectPixel (pixels-config.mjs:93:7)
    at async #onAction (pixels-config.mjs:71:9)
    
    
    
![image](https://github.com/user-attachments/assets/57803830-cbcc-4302-ada3-0ecbfa6db19c)

**Comment by Top64** [comment]
As Carrierfry was saying to me, this could be limited to the adapter. I will try with the laptop!
